# Generated by Django 3.0.7 on 2020-07-02 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=50)),
                ('head0', models.CharField(default='', max_length=50)),
                ('chead0', models.CharField(default='', max_length=500)),
                ('head1', models.CharField(default='', max_length=50)),
                ('chead1', models.CharField(default='', max_length=500)),
                ('head2', models.CharField(default='', max_length=50)),
                ('chead2', models.CharField(default='', max_length=500)),
                ('pub_date', models.DateField()),
                ('thumbnail', models.ImageField(default='', upload_to='blogs/images')),
            ],
        ),
    ]
